name: jsonp-pro Package

on:
  push:
    branches:
      - master

jobs:
  build:
    name: build files
    runs-on: macOS-latest
    steps:
      - uses: peng/jsonp-pro@master
        with:
          node-version: 12
      - run: yarn install
      - run: yarn test
      - run: yarn build

  publish-npm:
    needs: build
    runs-on: macOS-latest
    steps:
      - uses: peng/jsonp-pro@master
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUB_TOKEN}}
